### ISSUE TITLE
Fix not_analyzed for container_name

### ISSUE THREAD

**Issue by lukas-vlcek** [BitScoutOrg/elasticsearch-templates#78]
All of the index template files found in [0.0.12 release](https://github.com/ViaQ/elasticsearch-templates/releases/tag/0.0.12) contain strange mapping for `container_name` in `kubernetes` namespace.

Here is [link to the commit](https://github.com/ViaQ/elasticsearch-templates/commit/3a0fd28044bbb801bb68c694defeef61d2214854#diff-68ad33a0c66b0d664214552e39742836) that added the following yaml definition of `container_name` to `namespaces/kubernetes.yaml` file:

```yaml
 - name: container_name
    type: string
    norms:
      enabled: true
    description: >
      The name of the container in Kubernetes.
  fields:
      - name: raw
        ignore_above: 256
        type: string
```

This resulted to the following mapping (found in all three index template files in release 0.0.12):

```json
"container_name": {
  "type": "string",
  "index": "not_analyzed",   /*_<--_Here_!!!_*/
  "doc_values": true,
  "norms": {
    "enabled": true
  },
  "fields": {
    "raw": {
      "doc_values": true,
      "ignore_above": 256,
      "index": "not_analyzed",
      "type": "string"
    }
  }
}
```
The odd thing is that `container_name` value is **NOT ANALYZED**. This is either bug of makes the `container_name.raw` field redundant (as it is also NOT ANALYZED).
